package performance;

public enum BrakeParts {

    FIVE_STAR_GREEN_IMPROVED(4, 0, 20),
    FIVE_STAR_GREEN_SPORT(5, 0, 21),
    FIVE_STAR_GREEN_TUNED(5, 0, 23),
    FIVE_STAR_GREEN_CUSTOM(5, 0, 24),
    FIVE_STAR_GREEN_ELITE(5, 0, 25),

    FIVE_STAR_RED_IMPROVED(0, 0, 24),
    FIVE_STAR_RED_SPORT(0, 0, 26),
    FIVE_STAR_RED_TUNED(0, 0, 28),
    FIVE_STAR_RED_CUSTOM(0, 0, 29),
    FIVE_STAR_RED_ELITE(0, 0, 30),

    FIVE_STAR_BLUE_IMPROVED(0, 4, 20),
    FIVE_STAR_BLUE_SPORT(0, 5, 21),
    FIVE_STAR_BLUE_TUNED(0, 5, 23),
    FIVE_STAR_BLUE_CUSTOM(0, 5, 24),
    FIVE_STAR_BLUE_ELITE(0, 5, 25),

    FIVE_STAR_WHITE_IMPROVED(4, 4, 16),
    FIVE_STAR_WHITE_SPORT(5, 5, 16),
    FIVE_STAR_WHITE_TUNED(5, 5, 18),
    FIVE_STAR_WHITE_CUSTOM(5, 5, 19),
    FIVE_STAR_WHITE_ELITE(5, 5, 20),

    FOUR_STAR_RED_IMPROVED(0, 0, 18),
    FOUR_STAR_RED_SPORT(0, 0, 20),
    FOUR_STAR_RED_TUNED(0, 0, 22),
    FOUR_STAR_RED_CUSTOM(0, 0, 23),
    //FOUR_STAR_RED_ELITE(0, 0, 24),

    FOUR_STAR_GREEN_IMPROVED(3, 0, 15),
    FOUR_STAR_GREEN_SPORT(4, 0, 16),
    FOUR_STAR_GREEN_TUNED(4, 0, 18),
    FOUR_STAR_GREEN_CUSTOM(4, 0, 19),
    //FOUR_STAR_GREEN_ELITE(4, 0, 20),

    FOUR_STAR_BLUE_IMPROVED(0, 3, 15),
    FOUR_STAR_BLUE_SPORT(0, 4, 16),
    FOUR_STAR_BLUE_TUNED(0, 4, 18),
    FOUR_STAR_BLUE_CUSTOM(0, 4, 19),
    //FOUR_STAR_BLUE_ELITE(0, 4, 20),

    FOUR_STAR_WHITE_IMPROVED(3, 3, 12),
    FOUR_STAR_WHITE_SPORT(4, 4, 12),
    FOUR_STAR_WHITE_TUNED(4, 4, 14),
    FOUR_STAR_WHITE_CUSTOM(4, 4, 15),
    //FOUR_STAR_WHITE_ELITE(4, 4, 16),

    THREE_STAR_WHITE_IMPROVED(2, 2, 8),
    THREE_STAR_WHITE_SPORT(3, 3, 8),
    THREE_STAR_WHITE_TUNED(3, 3, 10),
    THREE_STAR_WHITE_CUSTOM(3, 3, 11),
    //THREE_STAR_WHITE_ELITE(3, 3, 12),

    THREE_STAR_BLUE_IMPROVED(0, 2, 10),
    THREE_STAR_BLUE_SPORT(0, 3, 11),
    THREE_STAR_BLUE_TUNED(0, 3, 13),
    THREE_STAR_BLUE_CUSTOM(0, 3, 14),
    //THREE_STAR_BLUE_ELITE(0, 3, 15),

    THREE_STAR_RED_IMPROVED(0, 0, 12),
    THREE_STAR_RED_SPORT(0, 0, 14),
    THREE_STAR_RED_TUNED(0, 0, 16),
    THREE_STAR_RED_CUSTOM(0, 0, 17),
    //THREE_STAR_RED_ELITE(0, 0, 18),

    THREE_STAR_GREEN_IMPROVED(2, 0, 10),
    THREE_STAR_GREEN_SPORT(3, 0, 11),
    THREE_STAR_GREEN_TUNED(3, 0, 13),
    THREE_STAR_GREEN_CUSTOM(3, 0, 14),
    //THREE_STAR_GREEN_ELITE(3, 0, 15),

    TWO_STAR_WHITE_IMPROVED(1, 1, 4),
    TWO_STAR_WHITE_SPORT(2, 2, 4),
    TWO_STAR_WHITE_TUNED(2, 2, 6),
    TWO_STAR_WHITE_CUSTOM(2, 2, 7),
    //TWO_STAR_WHITE_ELITE(2, 2, 8),

    TWO_STAR_BLUE_IMPROVED(0, 1, 5),
    TWO_STAR_BLUE_SPORT(0, 2, 6),
    TWO_STAR_BLUE_TUNED(0, 2, 8),
    TWO_STAR_BLUE_CUSTOM(0, 2, 9),
    //TWO_STAR_BLUE_ELITE(0, 2, 10),

    TWO_STAR_RED_IMPROVED(0, 0, 6),
    TWO_STAR_RED_SPORT(0, 0, 8),
    TWO_STAR_RED_TUNED(0, 0, 10),
    TWO_STAR_RED_CUSTOM(0, 0, 11),
    //TWO_STAR_RED_ELITE(0, 0, 12),

    TWO_STAR_GREEN_IMPROVED(1, 0, 5),
    TWO_STAR_GREEN_SPORT(2, 0, 6),
    TWO_STAR_GREEN_TUNED(2, 0, 8),
    TWO_STAR_GREEN_CUSTOM(2, 0, 9),
    //TWO_STAR_GREEN_ELITE(2, 0, 10),

    ONE_STAR_WHITE_IMPROVED(0, 0, 1),
    ONE_STAR_WHITE_SPORT(1, 1, 1),
    ONE_STAR_WHITE_TUNED(1, 1, 2),
    ONE_STAR_WHITE_CUSTOM(1, 1, 3),
    //ONE_STAR_WHITE_ELITE(1, 1, 4),

    ONE_STAR_BLUE_IMPROVED(0, 0, 1),
    ONE_STAR_BLUE_SPORT(0, 1, 2),
    ONE_STAR_BLUE_TUNED(0, 1, 3),
    ONE_STAR_BLUE_CUSTOM(0, 1, 4),
    //ONE_STAR_BLUE_ELITE(0, 1, 5),

    ONE_STAR_RED_IMPROVED(0, 0, 1),
    ONE_STAR_RED_SPORT(0, 0, 3),
    ONE_STAR_RED_TUNED(0, 0, 4),
    ONE_STAR_RED_CUSTOM(0, 0, 5),
    //ONE_STAR_RED_ELITE(0, 0, 6),

    ONE_STAR_GREEN_IMPROVED(0, 0, 1),
    ONE_STAR_GREEN_SPORT(1, 0, 2),
    ONE_STAR_GREEN_TUNED(1, 0, 3),
    ONE_STAR_GREEN_CUSTOM(1, 0, 4),
    //ONE_STAR_GREEN_ELITE(1, 0, 5),

    EMPTY(0,0,0)
    ;

    private int tGain, aGain, hGain;
    public static final BrakeParts[] VALUES = values();
    public static final BrakeParts[] GREEN_VALUES = {FIVE_STAR_GREEN_ELITE, FIVE_STAR_GREEN_CUSTOM, FIVE_STAR_GREEN_TUNED, FIVE_STAR_GREEN_SPORT, FIVE_STAR_GREEN_IMPROVED, FOUR_STAR_GREEN_CUSTOM, FOUR_STAR_GREEN_TUNED, FOUR_STAR_GREEN_SPORT, FOUR_STAR_GREEN_IMPROVED, THREE_STAR_GREEN_CUSTOM, THREE_STAR_GREEN_TUNED, THREE_STAR_GREEN_SPORT, THREE_STAR_GREEN_IMPROVED, TWO_STAR_GREEN_CUSTOM, TWO_STAR_GREEN_TUNED, TWO_STAR_GREEN_SPORT, TWO_STAR_GREEN_IMPROVED, ONE_STAR_GREEN_CUSTOM, ONE_STAR_GREEN_TUNED, ONE_STAR_GREEN_SPORT, ONE_STAR_GREEN_IMPROVED,EMPTY};
    public static final BrakeParts[] BLUE_VALUES = {FIVE_STAR_BLUE_ELITE, FIVE_STAR_BLUE_CUSTOM, FIVE_STAR_BLUE_TUNED, FIVE_STAR_BLUE_SPORT, FIVE_STAR_BLUE_IMPROVED, FOUR_STAR_BLUE_CUSTOM, FOUR_STAR_BLUE_TUNED, FOUR_STAR_BLUE_SPORT, FOUR_STAR_BLUE_IMPROVED, THREE_STAR_BLUE_CUSTOM, THREE_STAR_BLUE_TUNED, THREE_STAR_BLUE_SPORT, THREE_STAR_BLUE_IMPROVED, TWO_STAR_BLUE_CUSTOM, TWO_STAR_BLUE_TUNED, TWO_STAR_BLUE_SPORT, TWO_STAR_BLUE_IMPROVED, ONE_STAR_BLUE_CUSTOM, ONE_STAR_BLUE_TUNED, ONE_STAR_BLUE_SPORT, ONE_STAR_BLUE_IMPROVED,EMPTY};
    public static final BrakeParts[] RED_VALUES = {FIVE_STAR_RED_ELITE, FIVE_STAR_RED_CUSTOM, FIVE_STAR_RED_TUNED, FIVE_STAR_RED_SPORT, FIVE_STAR_RED_IMPROVED, FOUR_STAR_RED_CUSTOM, FOUR_STAR_RED_TUNED, FOUR_STAR_RED_SPORT, FOUR_STAR_RED_IMPROVED, THREE_STAR_RED_CUSTOM, THREE_STAR_RED_TUNED, THREE_STAR_RED_SPORT, THREE_STAR_RED_IMPROVED, TWO_STAR_RED_CUSTOM, TWO_STAR_RED_TUNED, TWO_STAR_RED_SPORT, TWO_STAR_RED_IMPROVED, ONE_STAR_RED_CUSTOM, ONE_STAR_RED_TUNED, ONE_STAR_RED_SPORT, ONE_STAR_RED_IMPROVED,EMPTY};
    public static final BrakeParts[] WHITE_VALUES = {FIVE_STAR_WHITE_ELITE, FIVE_STAR_WHITE_CUSTOM, FIVE_STAR_WHITE_TUNED, FIVE_STAR_WHITE_SPORT, FIVE_STAR_WHITE_IMPROVED, FOUR_STAR_WHITE_CUSTOM, FOUR_STAR_WHITE_TUNED, FOUR_STAR_WHITE_SPORT, FOUR_STAR_WHITE_IMPROVED, THREE_STAR_WHITE_CUSTOM, THREE_STAR_WHITE_TUNED, THREE_STAR_WHITE_SPORT, THREE_STAR_WHITE_IMPROVED, TWO_STAR_WHITE_CUSTOM, TWO_STAR_WHITE_TUNED, TWO_STAR_WHITE_SPORT, TWO_STAR_WHITE_IMPROVED, ONE_STAR_WHITE_CUSTOM, ONE_STAR_WHITE_TUNED, ONE_STAR_WHITE_SPORT, ONE_STAR_WHITE_IMPROVED,EMPTY};

    BrakeParts(int t, int a, int h) {
        this.tGain = t;
        this.hGain = h;
        this.aGain = a;
    }

    public int tGain() {
        return tGain;
    }

    public int aGain() {
        return aGain;
    }

    public int hGain() {
        return hGain;
    }

    @Override
    public String toString() {
        return ValueFilter.formattedName(this);
    }
}
