package performance;

import java.util.Locale;

public enum EngineParts {
    //5*
    //G
    FIVE_STAR_GREEN_IMPROVED(23, 11, 0),
    FIVE_STAR_GREEN_SPORT(24, 12, 0),
    FIVE_STAR_GREEN_TUNED(25, 13, 0),
    FIVE_STAR_GREEN_CUSTOM(26, 14, 0),
    FIVE_STAR_GREEN_ELITE(28, 14, 0),
    //W
    FIVE_STAR_WHITE_IMPROVED(17, 17, 0),
    FIVE_STAR_WHITE_SPORT(18, 18, 0),
    FIVE_STAR_WHITE_TUNED(19, 19, 0),
    FIVE_STAR_WHITE_CUSTOM(20, 20, 0),
    FIVE_STAR_WHITE_ELITE(21, 21, 0),
    //B
    FIVE_STAR_BLUE_IMPROVED(11, 23, 0),
    FIVE_STAR_BLUE_SPORT(12, 24, 0),
    FIVE_STAR_BLUE_TUNED(13, 25, 0),
    FIVE_STAR_BLUE_CUSTOM(14, 26, 0),
    FIVE_STAR_BLUE_ELITE(14, 28, 0),
    //R
    FIVE_STAR_RED_IMPROVED(17, 13, 4),
    FIVE_STAR_RED_SPORT(18, 13, 5),
    FIVE_STAR_RED_TUNED(19, 14, 5),
    FIVE_STAR_RED_CUSTOM(20, 15, 5),
    FIVE_STAR_RED_ELITE(21, 16, 5),

    //4*
    //G
    FOUR_STAR_GREEN_IMPROVED(18, 8, 0),
    FOUR_STAR_GREEN_SPORT(19, 9, 0),
    FOUR_STAR_GREEN_TUNED(20, 10, 0),
    FOUR_STAR_GREEN_CUSTOM(21, 11, 0),
    //FOUR_STAR_GREEN_ELITE(23, 11, 0),
    //W
    FOUR_STAR_WHITE_IMPROVED(13, 13, 0),
    FOUR_STAR_WHITE_SPORT(14, 14, 0),
    FOUR_STAR_WHITE_TUNED(15, 15, 0),
    FOUR_STAR_WHITE_CUSTOM(16, 16, 0),
    //FOUR_STAR_WHITE_ELITE(17, 17, 0),
    //B
    FOUR_STAR_BLUE_IMPROVED(8, 18, 0),
    FOUR_STAR_BLUE_SPORT(9, 19, 0),
    FOUR_STAR_BLUE_TUNED(10, 20, 0),
    FOUR_STAR_BLUE_CUSTOM(11, 21, 0),
    //FOUR_STAR_BLUE_ELITE(11, 23, 0),
    //R
    FOUR_STAR_RED_IMPROVED(13, 10, 3),
    FOUR_STAR_RED_SPORT(14, 10, 4),
    FOUR_STAR_RED_TUNED(15, 11, 4),
    FOUR_STAR_RED_CUSTOM(16, 12, 4),
    //FOUR_STAR_RED_ELITE(17, 13, 4),

    //3*
    //G
    THREE_STAR_GREEN_IMPROVED(13, 5, 0),
    THREE_STAR_GREEN_SPORT(14, 6, 0),
    THREE_STAR_GREEN_TUNED(15, 7, 0),
    THREE_STAR_GREEN_CUSTOM(16, 8, 0),
    //THREE_STAR_GREEN_ELITE(18, 8, 0),
    //W
    THREE_STAR_WHITE_IMPROVED(9, 9, 0),
    THREE_STAR_WHITE_SPORT(10, 10, 0),
    THREE_STAR_WHITE_TUNED(11, 11, 0),
    THREE_STAR_WHITE_CUSTOM(12, 12, 0),
    //THREE_STAR_WHITE_ELITE(13, 13, 0),
    //B
    THREE_STAR_BLUE_IMPROVED(5, 13, 0),
    THREE_STAR_BLUE_SPORT(6, 14, 0),
    THREE_STAR_BLUE_TUNED(7, 15, 0),
    THREE_STAR_BLUE_CUSTOM(8, 16, 0),
    //THREE_STAR_BLUE_ELITE(8, 18, 0),
    //R
    THREE_STAR_RED_IMPROVED(9, 7, 2),
    THREE_STAR_RED_SPORT(10, 7, 3),
    THREE_STAR_RED_TUNED(11, 8, 3),
    THREE_STAR_RED_CUSTOM(12, 9, 3),
    //THREE_STAR_RED_ELITE(13, 10, 3),

    //2*
    //G
    TWO_STAR_GREEN_IMPROVED(8, 2, 0),
    TWO_STAR_GREEN_SPORT(9, 3, 0),
    TWO_STAR_GREEN_TUNED(10, 4, 0),
    TWO_STAR_GREEN_CUSTOM(11, 5, 0),
    //TWO_STAR_GREEN_ELITE(13, 5, 0),
    //W
    TWO_STAR_WHITE_IMPROVED(5, 5, 0),
    TWO_STAR_WHITE_SPORT(6, 6, 0),
    TWO_STAR_WHITE_TUNED(7, 7, 0),
    TWO_STAR_WHITE_CUSTOM(8, 8, 0),
    //TWO_STAR_WHITE_ELITE(9, 9, 0),
    //B
    TWO_STAR_BLUE_IMPROVED(2, 8, 0),
    TWO_STAR_BLUE_SPORT(3, 9, 0),
    TWO_STAR_BLUE_TUNED(4, 10, 0),
    TWO_STAR_BLUE_CUSTOM(5, 11, 0),
    //TWO_STAR_BLUE_ELITE(5, 13, 0),
    //R
    TWO_STAR_RED_IMPROVED(5, 4, 1),
    TWO_STAR_RED_SPORT(6, 4, 2),
    TWO_STAR_RED_TUNED(7, 5, 2),
    TWO_STAR_RED_CUSTOM(8, 6, 2),
    //TWO_STAR_RED_ELITE(9, 7, 2),

    //1*
    //WHITE
    ONE_STAR_WHITE_IMPROVED(1, 1, 0),
    ONE_STAR_WHITE_SPORT(2, 2, 0),
    ONE_STAR_WHITE_TUNED(3, 3, 0),
    ONE_STAR_WHITE_CUSTOM(4, 4, 0),
    //ONE_STAR_WHITE_ELITE(5, 5, 0),

    //BLUE
    ONE_STAR_BLUE_IMPROVED(0, 2, 0),
    ONE_STAR_BLUE_SPORT(0, 4, 0),
    ONE_STAR_BLUE_TUNED(1, 5, 0),
    ONE_STAR_BLUE_CUSTOM(2, 6, 0),
    //ONE_STAR_BLUE_ELITE(2, 8, 0),


    //RED
    ONE_STAR_RED_IMPROVED(1,0, 1),
    ONE_STAR_RED_SPORT(2, 1, 1),
    ONE_STAR_RED_TUNED(3, 2, 1),
    ONE_STAR_RED_CUSTOM(4, 3, 1),
    //ONE_STAR_RED_ELITE(5, 4, 1),



    //GREEN
    ONE_STAR_GREEN_IMPROVED(2, 0, 0),
    ONE_STAR_GREEN_SPORT(4, 0, 0),
    ONE_STAR_GREEN_TUNED(5, 1, 0),
    ONE_STAR_GREEN_CUSTOM(6, 2, 0),
    //ONE_STAR_GREEN_ELITE(8, 2, 0),

    EMPTY(0,0,0)
    ;

    private int tGain, aGain, hGain;
    public static final EngineParts[] VALUES = values();
    //public static final EngineParts[] GREEN_VALUES = {FIVE_STAR_GREEN_ELITE, FIVE_STAR_GREEN_CUSTOM, FIVE_STAR_GREEN_TUNED, FIVE_STAR_GREEN_SPORT, FIVE_STAR_GREEN_IMPROVED, FOUR_STAR_GREEN_ELITE, FOUR_STAR_GREEN_CUSTOM, FOUR_STAR_GREEN_TUNED, FOUR_STAR_GREEN_SPORT, FOUR_STAR_GREEN_IMPROVED, THREE_STAR_GREEN_ELITE, THREE_STAR_GREEN_CUSTOM, THREE_STAR_GREEN_TUNED, THREE_STAR_GREEN_SPORT, THREE_STAR_GREEN_IMPROVED, TWO_STAR_GREEN_ELITE, TWO_STAR_GREEN_CUSTOM, TWO_STAR_GREEN_TUNED, TWO_STAR_GREEN_SPORT, TWO_STAR_GREEN_IMPROVED, ONE_STAR_GREEN_ELITE, ONE_STAR_GREEN_CUSTOM, ONE_STAR_GREEN_TUNED, ONE_STAR_GREEN_SPORT, ONE_STAR_GREEN_IMPROVED,EMPTY};
    //public static final EngineParts[] BLUE_VALUES = {FIVE_STAR_BLUE_ELITE, FIVE_STAR_BLUE_CUSTOM, FIVE_STAR_BLUE_TUNED, FIVE_STAR_BLUE_SPORT, FIVE_STAR_BLUE_IMPROVED, FOUR_STAR_BLUE_ELITE, FOUR_STAR_BLUE_CUSTOM, FOUR_STAR_BLUE_TUNED, FOUR_STAR_BLUE_SPORT, FOUR_STAR_BLUE_IMPROVED, THREE_STAR_BLUE_ELITE, THREE_STAR_BLUE_CUSTOM, THREE_STAR_BLUE_TUNED, THREE_STAR_BLUE_SPORT, THREE_STAR_BLUE_IMPROVED, TWO_STAR_BLUE_ELITE, TWO_STAR_BLUE_CUSTOM, TWO_STAR_BLUE_TUNED, TWO_STAR_BLUE_SPORT, TWO_STAR_BLUE_IMPROVED, ONE_STAR_BLUE_ELITE, ONE_STAR_BLUE_CUSTOM, ONE_STAR_BLUE_TUNED, ONE_STAR_BLUE_SPORT, ONE_STAR_BLUE_IMPROVED,EMPTY};
    //public static final EngineParts[] RED_VALUES = {FIVE_STAR_RED_ELITE, FIVE_STAR_RED_CUSTOM, FIVE_STAR_RED_TUNED, FIVE_STAR_RED_SPORT, FIVE_STAR_RED_IMPROVED, FOUR_STAR_RED_ELITE, FOUR_STAR_RED_CUSTOM, FOUR_STAR_RED_TUNED, FOUR_STAR_RED_SPORT, FOUR_STAR_RED_IMPROVED, THREE_STAR_RED_ELITE, THREE_STAR_RED_CUSTOM, THREE_STAR_RED_TUNED, THREE_STAR_RED_SPORT, THREE_STAR_RED_IMPROVED, TWO_STAR_RED_ELITE, TWO_STAR_RED_CUSTOM, TWO_STAR_RED_TUNED, TWO_STAR_RED_SPORT, TWO_STAR_RED_IMPROVED, ONE_STAR_RED_ELITE, ONE_STAR_RED_CUSTOM, ONE_STAR_RED_TUNED, ONE_STAR_RED_SPORT, ONE_STAR_RED_IMPROVED,EMPTY};
    //public static final EngineParts[] WHITE_VALUES = {FIVE_STAR_WHITE_ELITE, FIVE_STAR_WHITE_CUSTOM, FIVE_STAR_WHITE_TUNED, FIVE_STAR_WHITE_SPORT, FIVE_STAR_WHITE_IMPROVED, FOUR_STAR_WHITE_ELITE, FOUR_STAR_WHITE_CUSTOM, FOUR_STAR_WHITE_TUNED, FOUR_STAR_WHITE_SPORT, FOUR_STAR_WHITE_IMPROVED, THREE_STAR_WHITE_ELITE, THREE_STAR_WHITE_CUSTOM, THREE_STAR_WHITE_TUNED, THREE_STAR_WHITE_SPORT, THREE_STAR_WHITE_IMPROVED, TWO_STAR_WHITE_ELITE, TWO_STAR_WHITE_CUSTOM, TWO_STAR_WHITE_TUNED, TWO_STAR_WHITE_SPORT, TWO_STAR_WHITE_IMPROVED, ONE_STAR_WHITE_ELITE, ONE_STAR_WHITE_CUSTOM, ONE_STAR_WHITE_TUNED, ONE_STAR_WHITE_SPORT, ONE_STAR_WHITE_IMPROVED,EMPTY};
    public static final EngineParts[] GREEN_VALUES = {FIVE_STAR_GREEN_ELITE, FIVE_STAR_GREEN_CUSTOM, FIVE_STAR_GREEN_TUNED, FIVE_STAR_GREEN_SPORT, FIVE_STAR_GREEN_IMPROVED, FOUR_STAR_GREEN_CUSTOM, FOUR_STAR_GREEN_TUNED, FOUR_STAR_GREEN_SPORT, FOUR_STAR_GREEN_IMPROVED, THREE_STAR_GREEN_CUSTOM, THREE_STAR_GREEN_TUNED, THREE_STAR_GREEN_SPORT, THREE_STAR_GREEN_IMPROVED, TWO_STAR_GREEN_CUSTOM, TWO_STAR_GREEN_TUNED, TWO_STAR_GREEN_SPORT, TWO_STAR_GREEN_IMPROVED, ONE_STAR_GREEN_CUSTOM, ONE_STAR_GREEN_TUNED, ONE_STAR_GREEN_SPORT, ONE_STAR_GREEN_IMPROVED,EMPTY};
    public static final EngineParts[] BLUE_VALUES = {FIVE_STAR_BLUE_ELITE, FIVE_STAR_BLUE_CUSTOM, FIVE_STAR_BLUE_TUNED, FIVE_STAR_BLUE_SPORT, FIVE_STAR_BLUE_IMPROVED, FOUR_STAR_BLUE_CUSTOM, FOUR_STAR_BLUE_TUNED, FOUR_STAR_BLUE_SPORT, FOUR_STAR_BLUE_IMPROVED, THREE_STAR_BLUE_CUSTOM, THREE_STAR_BLUE_TUNED, THREE_STAR_BLUE_SPORT, THREE_STAR_BLUE_IMPROVED, TWO_STAR_BLUE_CUSTOM, TWO_STAR_BLUE_TUNED, TWO_STAR_BLUE_SPORT, TWO_STAR_BLUE_IMPROVED, ONE_STAR_BLUE_CUSTOM, ONE_STAR_BLUE_TUNED, ONE_STAR_BLUE_SPORT, ONE_STAR_BLUE_IMPROVED,EMPTY};
    public static final EngineParts[] RED_VALUES = {FIVE_STAR_RED_ELITE, FIVE_STAR_RED_CUSTOM, FIVE_STAR_RED_TUNED, FIVE_STAR_RED_SPORT, FIVE_STAR_RED_IMPROVED, FOUR_STAR_RED_CUSTOM, FOUR_STAR_RED_TUNED, FOUR_STAR_RED_SPORT, FOUR_STAR_RED_IMPROVED, THREE_STAR_RED_CUSTOM, THREE_STAR_RED_TUNED, THREE_STAR_RED_SPORT, THREE_STAR_RED_IMPROVED, TWO_STAR_RED_CUSTOM, TWO_STAR_RED_TUNED, TWO_STAR_RED_SPORT, TWO_STAR_RED_IMPROVED, ONE_STAR_RED_CUSTOM, ONE_STAR_RED_TUNED, ONE_STAR_RED_SPORT, ONE_STAR_RED_IMPROVED,EMPTY};
    public static final EngineParts[] WHITE_VALUES = {FIVE_STAR_WHITE_ELITE, FIVE_STAR_WHITE_CUSTOM, FIVE_STAR_WHITE_TUNED, FIVE_STAR_WHITE_SPORT, FIVE_STAR_WHITE_IMPROVED, FOUR_STAR_WHITE_CUSTOM, FOUR_STAR_WHITE_TUNED, FOUR_STAR_WHITE_SPORT, FOUR_STAR_WHITE_IMPROVED, THREE_STAR_WHITE_CUSTOM, THREE_STAR_WHITE_TUNED, THREE_STAR_WHITE_SPORT, THREE_STAR_WHITE_IMPROVED, TWO_STAR_WHITE_CUSTOM, TWO_STAR_WHITE_TUNED, TWO_STAR_WHITE_SPORT, TWO_STAR_WHITE_IMPROVED, ONE_STAR_WHITE_CUSTOM, ONE_STAR_WHITE_TUNED, ONE_STAR_WHITE_SPORT, ONE_STAR_WHITE_IMPROVED,EMPTY};



    /*static EngineParts[] sortValues() {
        EngineParts[] values = values();
        EngineParts[] parts = new EngineParts[values.length];
        for (int i = 0; i < parts.length; i++) {
            int index = i%5;
            if (index == 4) {
                parts[i-4] = values[i];
                parts[i-3] = values[i-1];
                parts[i-2] = values[i-2];
                parts[i-1] = values[i-3];
                parts[i] = values[i-4];
            }
        }
        parts[parts.length-1] = values[values.length-1];
        return parts;
    }
     */


    EngineParts(int t, int a, int h) {
        this.tGain = t;
        this.hGain = h;
        this.aGain = a;
    }

    public int tGain() {
        return tGain;
    }

    public int aGain() {
        return aGain;
    }

    public int hGain() {
        return hGain;
    }

    @Override
    public String toString() {
        return ValueFilter.formattedName(this);
    }
}
