package performance;

public enum SuspensionParts {

    FIVE_STAR_GREEN_IMPROVED(10, 8, 14),
    FIVE_STAR_GREEN_SPORT(10, 8, 15),
    FIVE_STAR_GREEN_TUNED(11, 9, 16),
    FIVE_STAR_GREEN_CUSTOM(12, 9, 17),
    FIVE_STAR_GREEN_ELITE(12, 10, 18),

    FIVE_STAR_RED_IMPROVED(-4, 8, 28),
    FIVE_STAR_RED_SPORT(-5, 8, 30),
    FIVE_STAR_RED_TUNED(-5, 9, 32),
    FIVE_STAR_RED_CUSTOM(-5, 9, 34),
    FIVE_STAR_RED_ELITE(-5, 10, 35),

    FIVE_STAR_BLUE_IMPROVED(-4, 24, 12),
    FIVE_STAR_BLUE_SPORT(-5, 25, 13),
    FIVE_STAR_BLUE_TUNED(-5, 27, 14),
    FIVE_STAR_BLUE_CUSTOM(-5, 28, 15),
    FIVE_STAR_BLUE_ELITE(-5, 30, 15),

    FIVE_STAR_WHITE_IMPROVED(4, 12, 16),
    FIVE_STAR_WHITE_SPORT(5, 12, 16),
    FIVE_STAR_WHITE_TUNED(5, 13, 18),
    FIVE_STAR_WHITE_CUSTOM(5, 14, 19),
    FIVE_STAR_WHITE_ELITE(5, 15, 20),

    FOUR_STAR_GREEN_IMPROVED(8, 6, 10),
    FOUR_STAR_GREEN_SPORT(8, 6, 11),
    FOUR_STAR_GREEN_TUNED(9, 7, 12),
    FOUR_STAR_GREEN_CUSTOM(10, 7, 13),
    //FOUR_STAR_GREEN_ELITE(10, 8, 14),

    FOUR_STAR_RED_IMPROVED(-3, 6, 21),
    FOUR_STAR_RED_SPORT(-4, 6, 23),
    FOUR_STAR_RED_TUNED(-4, 7, 25),
    FOUR_STAR_RED_CUSTOM(-4, 7, 27),
    //FOUR_STAR_RED_ELITE(-4, 8, 28),

    FOUR_STAR_BLUE_IMPROVED(-3, 18, 9),
    FOUR_STAR_BLUE_SPORT(-4, 19, 10),
    FOUR_STAR_BLUE_TUNED(-4, 21, 11),
    FOUR_STAR_BLUE_CUSTOM(-4, 22, 12),
    //FOUR_STAR_BLUE_ELITE(-4, 24, 12),

    FOUR_STAR_WHITE_IMPROVED(3, 9, 12),
    FOUR_STAR_WHITE_SPORT(4, 9, 12),
    FOUR_STAR_WHITE_TUNED(4, 10, 14),
    FOUR_STAR_WHITE_CUSTOM(4, 11, 15),
    //FOUR_STAR_WHITE_ELITE(4, 12, 16),

    THREE_STAR_WHITE_IMPROVED(2, 6, 8),
    THREE_STAR_WHITE_SPORT(3, 6, 8),
    THREE_STAR_WHITE_TUNED(3, 7, 10),
    THREE_STAR_WHITE_CUSTOM(3, 8, 11),
    //THREE_STAR_WHITE_ELITE(3, 9, 12),

    THREE_STAR_BLUE_IMPROVED(-2, 12, 6),
    THREE_STAR_BLUE_SPORT(-3, 13, 7),
    THREE_STAR_BLUE_TUNED(-3, 15, 8),
    THREE_STAR_BLUE_CUSTOM(-3, 16, 9),
    //THREE_STAR_BLUE_ELITE(-3, 18, 9),

    THREE_STAR_RED_IMPROVED(-2, 4, 14),
    THREE_STAR_RED_SPORT(-3, 4, 16),
    THREE_STAR_RED_TUNED(-3, 5, 18),
    THREE_STAR_RED_CUSTOM(-3, 5, 20),
    //THREE_STAR_RED_ELITE(-3, 6, 21),

    THREE_STAR_GREEN_IMPROVED(6, 4, 6),
    THREE_STAR_GREEN_SPORT(6, 4, 7),
    THREE_STAR_GREEN_TUNED(7, 5, 8),
    THREE_STAR_GREEN_CUSTOM(8, 5, 9),
    //THREE_STAR_GREEN_ELITE(8, 6, 10),

    TWO_STAR_WHITE_IMPROVED(1, 3, 4),
    TWO_STAR_WHITE_SPORT(2, 3, 4),
    TWO_STAR_WHITE_TUNED(2, 4, 6),
    TWO_STAR_WHITE_CUSTOM(2, 5, 7),
    //TWO_STAR_WHITE_ELITE(2, 6, 8),

    TWO_STAR_BLUE_IMPROVED(-1, 6, 3),
    TWO_STAR_BLUE_SPORT(-2, 7, 4),
    TWO_STAR_BLUE_TUNED(-2, 9, 5),
    TWO_STAR_BLUE_CUSTOM(-2, 10, 6),
    //TWO_STAR_BLUE_ELITE(-2, 12, 6),

    TWO_STAR_RED_IMPROVED(-1, 2, 7),
    TWO_STAR_RED_SPORT(-2, 2, 9),
    TWO_STAR_RED_TUNED(-2, 3, 11),
    TWO_STAR_RED_CUSTOM(-2, 3, 13),
    //TWO_STAR_RED_ELITE(-2, 4, 14),

    TWO_STAR_GREEN_IMPROVED(4, 2, 2),
    TWO_STAR_GREEN_SPORT(4, 2, 3),
    TWO_STAR_GREEN_TUNED(5, 3, 4),
    TWO_STAR_GREEN_CUSTOM(6, 3, 5),
    //TWO_STAR_GREEN_ELITE(6, 4, 6),

    ONE_STAR_WHITE_IMPROVED(0, 1, 0),
    ONE_STAR_WHITE_SPORT(1, 1, 1),
    ONE_STAR_WHITE_TUNED(1, 2, 2),
    ONE_STAR_WHITE_CUSTOM(1, 3, 3),
    //ONE_STAR_WHITE_ELITE(1, 3, 4),

    ONE_STAR_BLUE_IMPROVED(-1, 2, 0),
    ONE_STAR_BLUE_SPORT(-1, 3, 1),
    ONE_STAR_BLUE_TUNED(-1, 4, 2),
    ONE_STAR_BLUE_CUSTOM(-1, 5, 3),
    //ONE_STAR_BLUE_ELITE(-1, 6, 3),

    ONE_STAR_RED_IMPROVED(-1, 0, 2),
    ONE_STAR_RED_SPORT(-1, 1, 3),
    ONE_STAR_RED_TUNED(-1, 1, 5),
    ONE_STAR_RED_CUSTOM(-1, 2, 6),
    //ONE_STAR_RED_ELITE(-1, 2, 7),

    ONE_STAR_GREEN_IMPROVED(1, 0, 0),
    ONE_STAR_GREEN_SPORT(2, 0, 1),
    ONE_STAR_GREEN_TUNED(3, 1, 1),
    ONE_STAR_GREEN_CUSTOM(3, 2, 2),
    //ONE_STAR_GREEN_ELITE(4, 2, 2),

    EMPTY(0,0,0)

    ;

    private int tGain, aGain, hGain;
    public static final SuspensionParts[] VALUES = values();
    public static final SuspensionParts[] GREEN_VALUES = {FIVE_STAR_GREEN_ELITE, FIVE_STAR_GREEN_CUSTOM, FIVE_STAR_GREEN_TUNED, FIVE_STAR_GREEN_SPORT, FIVE_STAR_GREEN_IMPROVED, FOUR_STAR_GREEN_CUSTOM, FOUR_STAR_GREEN_TUNED, FOUR_STAR_GREEN_SPORT, FOUR_STAR_GREEN_IMPROVED, THREE_STAR_GREEN_CUSTOM, THREE_STAR_GREEN_TUNED, THREE_STAR_GREEN_SPORT, THREE_STAR_GREEN_IMPROVED, TWO_STAR_GREEN_CUSTOM, TWO_STAR_GREEN_TUNED, TWO_STAR_GREEN_SPORT, TWO_STAR_GREEN_IMPROVED, ONE_STAR_GREEN_CUSTOM, ONE_STAR_GREEN_TUNED, ONE_STAR_GREEN_SPORT, ONE_STAR_GREEN_IMPROVED,EMPTY};
    public static final SuspensionParts[] BLUE_VALUES = {FIVE_STAR_BLUE_ELITE, FIVE_STAR_BLUE_CUSTOM, FIVE_STAR_BLUE_TUNED, FIVE_STAR_BLUE_SPORT, FIVE_STAR_BLUE_IMPROVED, FOUR_STAR_BLUE_CUSTOM, FOUR_STAR_BLUE_TUNED, FOUR_STAR_BLUE_SPORT, FOUR_STAR_BLUE_IMPROVED, THREE_STAR_BLUE_CUSTOM, THREE_STAR_BLUE_TUNED, THREE_STAR_BLUE_SPORT, THREE_STAR_BLUE_IMPROVED, TWO_STAR_BLUE_CUSTOM, TWO_STAR_BLUE_TUNED, TWO_STAR_BLUE_SPORT, TWO_STAR_BLUE_IMPROVED, ONE_STAR_BLUE_CUSTOM, ONE_STAR_BLUE_TUNED, ONE_STAR_BLUE_SPORT, ONE_STAR_BLUE_IMPROVED,EMPTY};
    public static final SuspensionParts[] RED_VALUES = {FIVE_STAR_RED_ELITE, FIVE_STAR_RED_CUSTOM, FIVE_STAR_RED_TUNED, FIVE_STAR_RED_SPORT, FIVE_STAR_RED_IMPROVED, FOUR_STAR_RED_CUSTOM, FOUR_STAR_RED_TUNED, FOUR_STAR_RED_SPORT, FOUR_STAR_RED_IMPROVED, THREE_STAR_RED_CUSTOM, THREE_STAR_RED_TUNED, THREE_STAR_RED_SPORT, THREE_STAR_RED_IMPROVED, TWO_STAR_RED_CUSTOM, TWO_STAR_RED_TUNED, TWO_STAR_RED_SPORT, TWO_STAR_RED_IMPROVED, ONE_STAR_RED_CUSTOM, ONE_STAR_RED_TUNED, ONE_STAR_RED_SPORT, ONE_STAR_RED_IMPROVED,EMPTY};
    public static final SuspensionParts[] WHITE_VALUES = {FIVE_STAR_WHITE_ELITE, FIVE_STAR_WHITE_CUSTOM, FIVE_STAR_WHITE_TUNED, FIVE_STAR_WHITE_SPORT, FIVE_STAR_WHITE_IMPROVED, FOUR_STAR_WHITE_CUSTOM, FOUR_STAR_WHITE_TUNED, FOUR_STAR_WHITE_SPORT, FOUR_STAR_WHITE_IMPROVED, THREE_STAR_WHITE_CUSTOM, THREE_STAR_WHITE_TUNED, THREE_STAR_WHITE_SPORT, THREE_STAR_WHITE_IMPROVED, TWO_STAR_WHITE_CUSTOM, TWO_STAR_WHITE_TUNED, TWO_STAR_WHITE_SPORT, TWO_STAR_WHITE_IMPROVED, ONE_STAR_WHITE_CUSTOM, ONE_STAR_WHITE_TUNED, ONE_STAR_WHITE_SPORT, ONE_STAR_WHITE_IMPROVED,EMPTY};


    SuspensionParts(int t, int a, int h) {
        this.tGain = t;
        this.hGain = h;
        this.aGain = a;
    }

    public int tGain() {
        return tGain;
    }

    public int aGain() {
        return aGain;
    }

    public int hGain() {
        return hGain;
    }

    @Override
    public String toString() {
        return ValueFilter.formattedName(this);
    }
}
