package performance;

public enum TransmissionParts {

    FIVE_STAR_GREEN_IMPROVED(20, 10, 5),
    FIVE_STAR_GREEN_SPORT(21, 11, 5),
    FIVE_STAR_GREEN_TUNED(22, 11, 5),
    FIVE_STAR_GREEN_CUSTOM(23, 12, 5),
    FIVE_STAR_GREEN_ELITE(24, 12, 6),

    FIVE_STAR_RED_IMPROVED(10, 10, 15),
    FIVE_STAR_RED_SPORT(11, 11, 15),
    FIVE_STAR_RED_TUNED(11, 11, 16),
    FIVE_STAR_RED_CUSTOM(11, 11, 18),
    FIVE_STAR_RED_ELITE(12, 12, 18),

    FIVE_STAR_BLUE_IMPROVED(10, 20, 5),
    FIVE_STAR_BLUE_SPORT(11, 21, 5),
    FIVE_STAR_BLUE_TUNED(11, 22, 5),
    FIVE_STAR_BLUE_CUSTOM(12, 23, 5),
    FIVE_STAR_BLUE_ELITE(12, 24, 6),

    FIVE_STAR_WHITE_IMPROVED(15, 15, 5),
    FIVE_STAR_WHITE_SPORT(16, 16, 5),
    FIVE_STAR_WHITE_TUNED(16, 16, 6),
    FIVE_STAR_WHITE_CUSTOM(17, 17, 6),
    FIVE_STAR_WHITE_ELITE(18, 18, 6),

    FOUR_STAR_GREEN_IMPROVED(16, 8, 4),
    FOUR_STAR_GREEN_SPORT(17, 9, 4),
    FOUR_STAR_GREEN_TUNED(18, 9, 4),
    FOUR_STAR_GREEN_CUSTOM(19, 10, 4),
    //FOUR_STAR_GREEN_ELITE(20, 10, 5),

    FOUR_STAR_WHITE_IMPROVED(12, 12, 4),
    FOUR_STAR_WHITE_SPORT(13, 13, 4),
    FOUR_STAR_WHITE_TUNED(13, 13, 5),
    FOUR_STAR_WHITE_CUSTOM(14, 14, 5),
    //FOUR_STAR_WHITE_ELITE(15, 15, 5),

    FOUR_STAR_RED_IMPROVED(8, 8, 12),
    FOUR_STAR_RED_SPORT(9, 9, 12),
    FOUR_STAR_RED_TUNED(9, 9, 13),
    FOUR_STAR_RED_CUSTOM(9, 9, 15),
    //FOUR_STAR_RED_ELITE(10, 10, 15),

    FOUR_STAR_BLUE_IMPROVED(8, 16, 4),
    FOUR_STAR_BLUE_SPORT(9, 17, 4),
    FOUR_STAR_BLUE_TUNED(9, 18, 4),
    FOUR_STAR_BLUE_CUSTOM(10, 19, 4),
    //FOUR_STAR_BLUE_ELITE(10, 20, 5),

    THREE_STAR_WHITE_IMPROVED(9, 9, 3),
    THREE_STAR_WHITE_SPORT(10, 10, 3),
    THREE_STAR_WHITE_TUNED(10, 10, 4),
    THREE_STAR_WHITE_CUSTOM(11, 11, 4),
    //THREE_STAR_WHITE_ELITE(12, 12, 4),

    THREE_STAR_BLUE_IMPROVED(6, 12, 3),
    THREE_STAR_BLUE_SPORT(7, 13, 3),
    THREE_STAR_BLUE_TUNED(7, 14, 3),
    THREE_STAR_BLUE_CUSTOM(8, 15, 3),
    //THREE_STAR_BLUE_ELITE(8, 16, 4),

    THREE_STAR_RED_IMPROVED(6, 6, 9),
    THREE_STAR_RED_SPORT(7, 7, 9),
    THREE_STAR_RED_TUNED(7, 7, 10),
    THREE_STAR_RED_CUSTOM(7, 7, 12),
    //THREE_STAR_RED_ELITE(8, 8, 12),

    THREE_STAR_GREEN_IMPROVED(12, 6, 3),
    THREE_STAR_GREEN_SPORT(13, 7, 3),
    THREE_STAR_GREEN_TUNED(14, 7, 3),
    THREE_STAR_GREEN_CUSTOM(15, 8, 3),
    //THREE_STAR_GREEN_ELITE(16, 8, 4),

    TWO_STAR_WHITE_IMPROVED(6, 6, 2),
    TWO_STAR_WHITE_SPORT(7, 7, 2),
    TWO_STAR_WHITE_TUNED(7, 7, 3),
    TWO_STAR_WHITE_CUSTOM(8, 8, 3),
    //TWO_STAR_WHITE_ELITE(9, 9, 3),

    TWO_STAR_BLUE_IMPROVED(4, 8, 2),
    TWO_STAR_BLUE_SPORT(5, 9, 2),
    TWO_STAR_BLUE_TUNED(5, 10, 2),
    TWO_STAR_BLUE_CUSTOM(6, 11, 2),
    //TWO_STAR_BLUE_ELITE(6, 12, 3),

    TWO_STAR_RED_IMPROVED(4, 4, 6),
    TWO_STAR_RED_SPORT(5, 5, 6),
    TWO_STAR_RED_TUNED(5, 5, 7),
    TWO_STAR_RED_CUSTOM(5, 5, 9),
    //TWO_STAR_RED_ELITE(6, 6, 9),

    TWO_STAR_GREEN_IMPROVED(8, 4, 2),
    TWO_STAR_GREEN_SPORT(9, 5, 2),
    TWO_STAR_GREEN_TUNED(10, 5, 2),
    TWO_STAR_GREEN_CUSTOM(11, 6, 2),
    //TWO_STAR_GREEN_ELITE(12, 6, 3),

    ONE_STAR_WHITE_IMPROVED(2, 2, 0),
    ONE_STAR_WHITE_SPORT(3, 3, 1),
    ONE_STAR_WHITE_TUNED(4, 4, 1),
    ONE_STAR_WHITE_CUSTOM(5, 5, 1),
    //ONE_STAR_WHITE_ELITE(6, 6, 2),

    ONE_STAR_BLUE_IMPROVED(0, 4, 0),
    ONE_STAR_BLUE_SPORT(1, 5, 1),
    ONE_STAR_BLUE_TUNED(2, 6, 1),
    ONE_STAR_BLUE_CUSTOM(3, 7, 1),
    //ONE_STAR_BLUE_ELITE(4, 8, 2),

    ONE_STAR_RED_IMPROVED(1, 1, 2),
    ONE_STAR_RED_SPORT(2, 2, 3),
    ONE_STAR_RED_TUNED(3, 3, 3),
    ONE_STAR_RED_CUSTOM(3, 3, 5),
    //ONE_STAR_RED_ELITE(4, 4, 6),

    ONE_STAR_GREEN_IMPROVED(4, 0, 0),
    ONE_STAR_GREEN_SPORT(5, 1, 1),
    ONE_STAR_GREEN_TUNED(6, 2, 1),
    ONE_STAR_GREEN_CUSTOM(7, 3, 1),
    //ONE_STAR_GREEN_ELITE(8, 4, 2),

    EMPTY(0,0,0)
    ;

    private int tGain, aGain, hGain;
    public static final TransmissionParts[] VALUES = values();
    public static final TransmissionParts[] GREEN_VALUES = {FIVE_STAR_GREEN_ELITE, FIVE_STAR_GREEN_CUSTOM, FIVE_STAR_GREEN_TUNED, FIVE_STAR_GREEN_SPORT, FIVE_STAR_GREEN_IMPROVED, FOUR_STAR_GREEN_CUSTOM, FOUR_STAR_GREEN_TUNED, FOUR_STAR_GREEN_SPORT, FOUR_STAR_GREEN_IMPROVED, THREE_STAR_GREEN_CUSTOM, THREE_STAR_GREEN_TUNED, THREE_STAR_GREEN_SPORT, THREE_STAR_GREEN_IMPROVED, TWO_STAR_GREEN_CUSTOM, TWO_STAR_GREEN_TUNED, TWO_STAR_GREEN_SPORT, TWO_STAR_GREEN_IMPROVED, ONE_STAR_GREEN_CUSTOM, ONE_STAR_GREEN_TUNED, ONE_STAR_GREEN_SPORT, ONE_STAR_GREEN_IMPROVED,EMPTY};
    public static final TransmissionParts[] BLUE_VALUES = {FIVE_STAR_BLUE_ELITE, FIVE_STAR_BLUE_CUSTOM, FIVE_STAR_BLUE_TUNED, FIVE_STAR_BLUE_SPORT, FIVE_STAR_BLUE_IMPROVED, FOUR_STAR_BLUE_CUSTOM, FOUR_STAR_BLUE_TUNED, FOUR_STAR_BLUE_SPORT, FOUR_STAR_BLUE_IMPROVED, THREE_STAR_BLUE_CUSTOM, THREE_STAR_BLUE_TUNED, THREE_STAR_BLUE_SPORT, THREE_STAR_BLUE_IMPROVED, TWO_STAR_BLUE_CUSTOM, TWO_STAR_BLUE_TUNED, TWO_STAR_BLUE_SPORT, TWO_STAR_BLUE_IMPROVED, ONE_STAR_BLUE_CUSTOM, ONE_STAR_BLUE_TUNED, ONE_STAR_BLUE_SPORT, ONE_STAR_BLUE_IMPROVED,EMPTY};
    public static final TransmissionParts[] RED_VALUES = {FIVE_STAR_RED_ELITE, FIVE_STAR_RED_CUSTOM, FIVE_STAR_RED_TUNED, FIVE_STAR_RED_SPORT, FIVE_STAR_RED_IMPROVED, FOUR_STAR_RED_CUSTOM, FOUR_STAR_RED_TUNED, FOUR_STAR_RED_SPORT, FOUR_STAR_RED_IMPROVED, THREE_STAR_RED_CUSTOM, THREE_STAR_RED_TUNED, THREE_STAR_RED_SPORT, THREE_STAR_RED_IMPROVED, TWO_STAR_RED_CUSTOM, TWO_STAR_RED_TUNED, TWO_STAR_RED_SPORT, TWO_STAR_RED_IMPROVED, ONE_STAR_RED_CUSTOM, ONE_STAR_RED_TUNED, ONE_STAR_RED_SPORT, ONE_STAR_RED_IMPROVED,EMPTY};
    public static final TransmissionParts[] WHITE_VALUES = {FIVE_STAR_WHITE_ELITE, FIVE_STAR_WHITE_CUSTOM, FIVE_STAR_WHITE_TUNED, FIVE_STAR_WHITE_SPORT, FIVE_STAR_WHITE_IMPROVED, FOUR_STAR_WHITE_CUSTOM, FOUR_STAR_WHITE_TUNED, FOUR_STAR_WHITE_SPORT, FOUR_STAR_WHITE_IMPROVED, THREE_STAR_WHITE_CUSTOM, THREE_STAR_WHITE_TUNED, THREE_STAR_WHITE_SPORT, THREE_STAR_WHITE_IMPROVED, TWO_STAR_WHITE_CUSTOM, TWO_STAR_WHITE_TUNED, TWO_STAR_WHITE_SPORT, TWO_STAR_WHITE_IMPROVED, ONE_STAR_WHITE_CUSTOM, ONE_STAR_WHITE_TUNED, ONE_STAR_WHITE_SPORT, ONE_STAR_WHITE_IMPROVED,EMPTY};

    TransmissionParts(int t, int a, int h) {
        this.tGain = t;
        this.hGain = h;
        this.aGain = a;
    }

    public int tGain() {
        return tGain;
    }

    public int aGain() {
        return aGain;
    }

    public int hGain() {
        return hGain;
    }

    @Override
    public String toString() {
        return ValueFilter.formattedName(this);
    }
}
