package performance;

public enum TurboParts {

    FIVE_STAR_GREEN_IMPROVED(23, 11, -4),
    FIVE_STAR_GREEN_SPORT(24, 12, -5),
    FIVE_STAR_GREEN_TUNED(25, 13, -5),
    FIVE_STAR_GREEN_CUSTOM(26, 14, -5),
    FIVE_STAR_GREEN_ELITE(28, 14, -5),

    FIVE_STAR_RED_IMPROVED(13, 17, 0),
    FIVE_STAR_RED_SPORT(13, 18, 0),
    FIVE_STAR_RED_TUNED(14, 19, 0),
    FIVE_STAR_RED_CUSTOM(15, 20, 0),
    FIVE_STAR_RED_ELITE(16, 21, 0),

    FIVE_STAR_BLUE_IMPROVED(11, 23, -4),
    FIVE_STAR_BLUE_SPORT(12, 24, -5),
    FIVE_STAR_BLUE_TUNED(13, 25, -5),
    FIVE_STAR_BLUE_CUSTOM(14, 26, -5),
    FIVE_STAR_BLUE_ELITE(14, 28, -5),

    FIVE_STAR_WHITE_IMPROVED(17, 17, -4),
    FIVE_STAR_WHITE_SPORT(18, 18, -5),
    FIVE_STAR_WHITE_TUNED(19, 19, -5),
    FIVE_STAR_WHITE_CUSTOM(20, 20, -5),
    FIVE_STAR_WHITE_ELITE(21, 21, -5),

    FOUR_STAR_GREEN_IMPROVED(18, 8, -3),
    FOUR_STAR_GREEN_SPORT(19, 9, -4),
    FOUR_STAR_GREEN_TUNED(20, 10, -4),
    FOUR_STAR_GREEN_CUSTOM(21, 11, -4),
    //FOUR_STAR_GREEN_ELITE(23, 11, -4),

    FOUR_STAR_RED_IMPROVED(10, 13, 0),
    FOUR_STAR_RED_SPORT(10, 14, 0),
    FOUR_STAR_RED_TUNED(11, 15, 0),
    FOUR_STAR_RED_CUSTOM(12, 16, 0),
    //FOUR_STAR_RED_ELITE(13, 17, 0),

    FOUR_STAR_BLUE_IMPROVED(8, 18, -3),
    FOUR_STAR_BLUE_SPORT(9, 19, -4),
    FOUR_STAR_BLUE_TUNED(10, 20, -4),
    FOUR_STAR_BLUE_CUSTOM(11, 21, -4),
    //FOUR_STAR_BLUE_ELITE(11, 23, -4),

    FOUR_STAR_WHITE_IMPROVED(13, 13, -3),
    FOUR_STAR_WHITE_SPORT(14, 14, -4),
    FOUR_STAR_WHITE_TUNED(15, 15, -4),
    FOUR_STAR_WHITE_CUSTOM(16, 16, -4),
    //FOUR_STAR_WHITE_ELITE(17, 17, -4),

    THREE_STAR_GREEN_IMPROVED(13, 5, -2),
    THREE_STAR_GREEN_SPORT(14, 6, -3),
    THREE_STAR_GREEN_TUNED(15, 7, -3),
    THREE_STAR_GREEN_CUSTOM(16, 8, -3),
    //THREE_STAR_GREEN_ELITE(18, 8, -3),

    THREE_STAR_RED_IMPROVED(7, 9, 0),
    THREE_STAR_RED_SPORT(7, 10, 0),
    THREE_STAR_RED_TUNED(8, 11, 0),
    THREE_STAR_RED_CUSTOM(9, 12, 0),
    //THREE_STAR_RED_ELITE(10, 13, 0),

    THREE_STAR_BLUE_IMPROVED(5, 13, -2),
    THREE_STAR_BLUE_SPORT(6, 14, -3),
    THREE_STAR_BLUE_TUNED(7, 15, -3),
    THREE_STAR_BLUE_CUSTOM(8, 16, -3),
    //THREE_STAR_BLUE_ELITE(8, 18, -3),

    THREE_STAR_WHITE_IMPROVED(9, 9, -2),
    THREE_STAR_WHITE_SPORT(10, 10, -3),
    THREE_STAR_WHITE_TUNED(11, 11, -3),
    THREE_STAR_WHITE_CUSTOM(12, 12, -3),
    //THREE_STAR_WHITE_ELITE(13, 13, -3),

    TWO_STAR_GREEN_IMPROVED(8, 2, -1),
    TWO_STAR_GREEN_SPORT(9, 3, -2),
    TWO_STAR_GREEN_TUNED(10, 4, -2),
    TWO_STAR_GREEN_CUSTOM(11, 5, -2),
    //TWO_STAR_GREEN_ELITE(13, 5, -2),

    TWO_STAR_RED_IMPROVED(4, 5, 0),
    TWO_STAR_RED_SPORT(4, 6, 0),
    TWO_STAR_RED_TUNED(5, 7, 0),
    TWO_STAR_RED_CUSTOM(6, 8, 0),
    //TWO_STAR_RED_ELITE(7, 9, 0),

    TWO_STAR_BLUE_IMPROVED(2, 8, -1),
    TWO_STAR_BLUE_SPORT(3, 9, -2),
    TWO_STAR_BLUE_TUNED(4, 10, -2),
    TWO_STAR_BLUE_CUSTOM(5, 11, -2),
    //TWO_STAR_BLUE_ELITE(5, 13, -2),

    TWO_STAR_WHITE_IMPROVED(5, 5, -1),
    TWO_STAR_WHITE_SPORT(6, 6, -2),
    TWO_STAR_WHITE_TUNED(7, 7, -2),
    TWO_STAR_WHITE_CUSTOM(8, 8, -2),
    //TWO_STAR_WHITE_ELITE(9, 9, -2),

    ONE_STAR_WHITE_IMPROVED(1, 1, -1),
    ONE_STAR_WHITE_SPORT(2, 2, -1),
    ONE_STAR_WHITE_TUNED(3, 3, -1),
    ONE_STAR_WHITE_CUSTOM(4, 4, -1),
    //ONE_STAR_WHITE_ELITE(5, 5, -1),

    ONE_STAR_BLUE_IMPROVED(0, 2, -1),
    ONE_STAR_BLUE_SPORT(0, 4, -1),
    ONE_STAR_BLUE_TUNED(1, 5, -1),
    ONE_STAR_BLUE_CUSTOM(2, 6, -1),
    //ONE_STAR_BLUE_ELITE(2, 8, -1),

    ONE_STAR_RED_IMPROVED(0,1, 0),
    ONE_STAR_RED_SPORT(1, 2, 0),
    ONE_STAR_RED_TUNED(2, 3, 0),
    ONE_STAR_RED_CUSTOM(3, 4, 0),
    //ONE_STAR_RED_ELITE(4, 5, 0),

    ONE_STAR_GREEN_IMPROVED(2, 0, -1),
    ONE_STAR_GREEN_SPORT(4, 0, -1),
    ONE_STAR_GREEN_TUNED(5, 1, -1),
    ONE_STAR_GREEN_CUSTOM(6, 2, -1),
    //ONE_STAR_GREEN_ELITE(8, 2, -1),

    EMPTY(0,0,0)
    ;

    private int tGain, aGain, hGain;
    public static final TurboParts[] VALUES = values();
    public static final TurboParts[] GREEN_VALUES = {FIVE_STAR_GREEN_ELITE, FIVE_STAR_GREEN_CUSTOM, FIVE_STAR_GREEN_TUNED, FIVE_STAR_GREEN_SPORT, FIVE_STAR_GREEN_IMPROVED, FOUR_STAR_GREEN_CUSTOM, FOUR_STAR_GREEN_TUNED, FOUR_STAR_GREEN_SPORT, FOUR_STAR_GREEN_IMPROVED, THREE_STAR_GREEN_CUSTOM, THREE_STAR_GREEN_TUNED, THREE_STAR_GREEN_SPORT, THREE_STAR_GREEN_IMPROVED, TWO_STAR_GREEN_CUSTOM, TWO_STAR_GREEN_TUNED, TWO_STAR_GREEN_SPORT, TWO_STAR_GREEN_IMPROVED, ONE_STAR_GREEN_CUSTOM, ONE_STAR_GREEN_TUNED, ONE_STAR_GREEN_SPORT, ONE_STAR_GREEN_IMPROVED,EMPTY};
    public static final TurboParts[] BLUE_VALUES = {FIVE_STAR_BLUE_ELITE, FIVE_STAR_BLUE_CUSTOM, FIVE_STAR_BLUE_TUNED, FIVE_STAR_BLUE_SPORT, FIVE_STAR_BLUE_IMPROVED, FOUR_STAR_BLUE_CUSTOM, FOUR_STAR_BLUE_TUNED, FOUR_STAR_BLUE_SPORT, FOUR_STAR_BLUE_IMPROVED, THREE_STAR_BLUE_CUSTOM, THREE_STAR_BLUE_TUNED, THREE_STAR_BLUE_SPORT, THREE_STAR_BLUE_IMPROVED, TWO_STAR_BLUE_CUSTOM, TWO_STAR_BLUE_TUNED, TWO_STAR_BLUE_SPORT, TWO_STAR_BLUE_IMPROVED, ONE_STAR_BLUE_CUSTOM, ONE_STAR_BLUE_TUNED, ONE_STAR_BLUE_SPORT, ONE_STAR_BLUE_IMPROVED,EMPTY};
    public static final TurboParts[] RED_VALUES = {FIVE_STAR_RED_ELITE, FIVE_STAR_RED_CUSTOM, FIVE_STAR_RED_TUNED, FIVE_STAR_RED_SPORT, FIVE_STAR_RED_IMPROVED, FOUR_STAR_RED_CUSTOM, FOUR_STAR_RED_TUNED, FOUR_STAR_RED_SPORT, FOUR_STAR_RED_IMPROVED, THREE_STAR_RED_CUSTOM, THREE_STAR_RED_TUNED, THREE_STAR_RED_SPORT, THREE_STAR_RED_IMPROVED, TWO_STAR_RED_CUSTOM, TWO_STAR_RED_TUNED, TWO_STAR_RED_SPORT, TWO_STAR_RED_IMPROVED, ONE_STAR_RED_CUSTOM, ONE_STAR_RED_TUNED, ONE_STAR_RED_SPORT, ONE_STAR_RED_IMPROVED,EMPTY};
    public static final TurboParts[] WHITE_VALUES = {FIVE_STAR_WHITE_ELITE, FIVE_STAR_WHITE_CUSTOM, FIVE_STAR_WHITE_TUNED, FIVE_STAR_WHITE_SPORT, FIVE_STAR_WHITE_IMPROVED, FOUR_STAR_WHITE_CUSTOM, FOUR_STAR_WHITE_TUNED, FOUR_STAR_WHITE_SPORT, FOUR_STAR_WHITE_IMPROVED, THREE_STAR_WHITE_CUSTOM, THREE_STAR_WHITE_TUNED, THREE_STAR_WHITE_SPORT, THREE_STAR_WHITE_IMPROVED, TWO_STAR_WHITE_CUSTOM, TWO_STAR_WHITE_TUNED, TWO_STAR_WHITE_SPORT, TWO_STAR_WHITE_IMPROVED, ONE_STAR_WHITE_CUSTOM, ONE_STAR_WHITE_TUNED, ONE_STAR_WHITE_SPORT, ONE_STAR_WHITE_IMPROVED,EMPTY};

    TurboParts(int t, int a, int h) {
        this.tGain = t;
        this.hGain = h;
        this.aGain = a;
    }

    public int tGain() {
        return tGain;
    }

    public int aGain() {
        return aGain;
    }

    public int hGain() {
        return hGain;
    }

    @Override
    public String toString() {
        return ValueFilter.formattedName(this);
    }
}
